parameters:
    raulfraile_apijokes_email_from: raulfraile@gmail.com
    raulfraile_apijokes_email_to: raulfraile@gmail.com

services:
    raulfraile.listener.joke.emailer:
        class:        "RaulFraile\\ApiJokesBundle\\EventListener\\JokeEmailer"
        arguments:    ['@mailer', '@templating', '%raulfraile_apijokes_email_from%', '%raulfraile_apijokes_email_to%']
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }